language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install rdflib rdflib-jsonld
  # for testing:
  - pip install misaka
script:
  - py.test
  - pep8 --ignore=E501 *.py */*.py
  - pep257 *.py */*.py
  - rst-lint README
